### ISSUE TITLE
Crash in release mode

### ISSUE THREAD

**Issue by uaktech** [cleveradssolutions/CAS-Android#11]
I am using 

casAds = { id = "com.cleveradssolutions.gradle-plugin", version = "4.0.0-beta8" }

in debug mode its works fine but in release mode it crashes and five Firebase.iniliaze error
I try with down grading firebase and many other way but not able to run with release version

**Comment by Str4tos** [comment]
Hi, @uaktech 

Thank you for creating the issue. We don't have enough information from what you've provided. Could you please share the complete log file from your device during the app crash?

Also, any additional information that could help us better understand the problem would be greatly appreciated, as it will allow us to find a solution more quickly.

Thank you.

**Comment by uaktech** [comment]
i am facing this issue

          Process: com.app.check:AppMetrica, PID: 26413
                                                                                                    java.lang.RuntimeException: Unable to create application com.appapplicationclass.MyApplication: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.app.check:AppMetrica. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
                                                                                                    	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7356)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
                                                                                                    Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.app.check:AppMetrica. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                                                    	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:179)
                                                                                                    	at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance(FirebaseRemoteConfig.java:81)
                                                                                                    	at com.app.check.module.ApiModule.provideFirebaseRemoteConfig(ApiModule.kt:29)
                                                                                                    	at com.app.check.module.ApiModule_ProvideFirebaseRemoteConfigFactory.provideFirebaseRemoteConfig(ApiModule_ProvideFirebaseRemoteConfigFactory.java:36)
                                                                                                    	at com.app.check.applicationclass.DaggerMyApplication_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerMyApplication_HiltComponents_SingletonC.java:1487)
                                                                                                    	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                                                                                                    	at com.app.check.applicationclass.DaggerMyApplication_HiltComponents_SingletonC$SingletonCImpl.injectMyApplication2(DaggerMyApplication_HiltComponents_SingletonC.java:1465)
                                                                                                    	at com.app.check.applicationclass.DaggerMyApplication_HiltComponents_SingletonC$SingletonCImpl.injectMyApplication(DaggerMyApplication_HiltComponents_SingletonC.java:1444)
                                                                                                    	at com.app.check.applicationclass.Hilt_MyApplication.hiltInternalInject(Hilt_MyApplication.java:49)
                                                                                                    	at com.app.check.applicationclass.Hilt_MyApplication.onCreate(Hilt_MyApplication.java:40)
                                                                                                    	at com.app.check.applicationclass.MyApplication.onCreate(MyApplication.kt:43)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
                                                                                                    	at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loop(Looper.java:214) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7356) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by uaktech** [comment]
app shows dialogs keeps stopping and generates that crash in release mode in debug mood its working fine

**Comment by Str4tos** [comment]
The issue you're encountering is related to Yandex Mobile Ads and its dependency on AppMetrica, which creates an additional process for your app with the suffix :AppMetrica. Please check your onCreate() method in the Application class implementation. Make sure you are initializing any third-party libraries only in the main process of your app.

If this is already the case and you're still encountering the error, it means that one of the Firebase services is being initialized automatically for each app process. In that case, you need to initialize Firebase for each app process, as described in the error message.

You can read more about this on the official AppMetrica website:
- [Error initializing AppMetrica with third-party libraries](https://yandex.ru/support2/appmetrica-io/en/sdk/android/analytics/android-errors#third-party-library-init)

Or in the adapted version for the CAS SDK in our Wiki section: 
- [Additional Yandex Mobile Ads steps](https://github.com/cleveradssolutions/CAS-Android/wiki/Additional-Yandex-Mobile-Ads-steps)

Let us know if you were able to resolve the issue.

**Comment by uaktech** [comment]
okay, Let me check I will let you know, thanks for help

**Comment by uaktech** [comment]
removing yandex ads solves the problem
